### ISSUE TITLE
Favicons Default values - doesn't work

### ISSUE THREAD

**Issue by qdelski** [gioppy/statamic-metatags#10]
I think there is a bug, when "OTHER META TAGS" "Favicons" are enabled. I've uploaded default icons in "Meta Tags > Defaults", and they do not appear, i get empty <link> tags.

I did test, and after adding "metadata" fieldset to my blueprint, and then editing specific page, and then add some icons, it is working as should.

So I've made dumps in your "metatags.antlers.html" displaying "fields", and it seems that problem is that default values, and page specific values are stored differentely defaults are "string", and fieldset values are full array, eg.:
 
**- Page with default settings only has data displayed like this:**
`"favicons_apple_touch_icon" => Statamic\Fields\Value {#7580 ▼
    #raw: "gfx/favicons/apple-touch-icon.png"
    #handle: null
    #fieldtype: null
    #augmentable: null
    #shallow: false
  }`
so looking for url property results in empty value : ` {{ if favicons_apple_touch_icon }}<link rel="apple-touch-icon" sizes="180x180" href="{{ favicons_apple_touch_icon.url }}">{{ /if }}`

**- Page with default value overwritten for specific page:**
`"favicons_apple_touch_icon" => Statamic\Fields\Value {#3355 ▼
    #raw: array:46 [▼
      "alt" => " favicon"
      "id" => "assets::gfx/favicons/apple-touch-icon.png"
      "title" => "apple-touch-icon.png"
      "path" => "gfx/favicons/apple-touch-icon.png"
      "filename" => "apple-touch-icon"
      "basename" => "apple-touch-icon.png"
      "extension" => "png"
      "is_asset" => true
      "is_audio" => false
      "is_previewable" => false
      "is_image" => true
      "is_svg" => false
      "is_video" => false
      "blueprint" => array:2 [▶]
      "edit_url" => "/cp/assets/browse/assets/gfx/favicons/apple-touch-icon.png/edit"
      "container" => array:7 [▶]
      "folder" => "gfx/favicons"
      "url" => "/assets/gfx/favicons/apple-touch-icon.png"
      "permalink" => "/assets/gfx/favicons/apple-touch-icon.png"
      "api_url" => null
      "size" => "2.79 KB"
      "size_bytes" => 2858
      "size_kilobytes" => 2.79
      "size_megabytes" => 0.0
      "size_gigabytes" => 0.0
      "size_b" => 2858
      "size_kb" => 2.79
      "size_mb" => 0.0
      "size_gb" => 0.0
      "last_modified" => Illuminate\Support\Carbon @1692693030 {#4402 ▶}
      "last_modified_timestamp" => 1692693030
      "last_modified_instance" => Illuminate\Support\Carbon @1692693030 {#4413 ▶}
      "focus" => "50-50-1"
      "has_focus" => false
      "focus_css" => "50% 50%"
      "height" => 180
      "width" => 180
      "orientation" => "square"
      "ratio" => 1
      "mime_type" => "image/png"
      "duration" => 0.0
      "duration_seconds" => 0.0
      "duration_minutes" => null
      "duration_sec" => 0.0
      "duration_min" => null
      "playtime" => "00:00"
    ]
    #handle: null
    #fieldtype: null
    #augmentable: null
    #shallow: false
  }`

I do not know, if i do something wrong, or this is a bug.

**Comment by gioppy** [comment]
Thanks for the issue: i've update the addon, so you can `composer update gioppy/statamic-metatags`. Now the values will be printed correctly.
Feel free to reopen the issue if the problem persist.

**Comment by qdelski** [comment]
Thank you @gioppy  for a bugfix on Favicons, it is working, but now all fields keys `$fields->all()` in `vendor\gioppy\statamic-metatags\src\Tags\MetatagsTags.php` are always there, so when there is no Basic Meta Tags - Page Title title field condition is always false:

//Check if fields have title, otherwise load default title
if (!array_key_exists('basic_title', $fields->all())) {
      $defaultTitle = $page->only('title')->all();
      $fields->prepend(new Value($defaultTitle['title']), 'basic_title');
} 

, because there is "basic_title" key with no value, So if I do not have Page Title anywhere added, it does't generate <title> tag. Checking basic_title value instead of key, would fix it.

**Comment by qdelski** [comment]
`if (!array_key_exists('basic_title', $fields->all()) || !is_string($fields->all()["basic_title"])) {`

I did some manual fix to make this work, as it starterd to be urgent. Don't know if this is best possible way, but it's working. 

UPDATE: 11.10.23 
Unfortunately this is not way to do with Error Pages, i use Statamic default error routes, so they do not have special page, and 404 page generates error on line:
`$fields->prepend(new Value($defaultTitle['title']), 'basic_title');`
because of uknown "title" field.

**Comment by gioppy** [comment]
You have right: the title is missing! I push a new version with the fix. Unfortunaly, at this time, there is no possibile to set meta tags for 404 page (maybe in the future). Hovewer I set empty title for this cases, instead of an error!

Please, feel free to reopen the issue if the problem persist.
