### ISSUE TITLE
Statamic Update to version above 4.28.0 - library crashes App

### ISSUE THREAD

**Issue by qdelski** [gioppy/statamic-metatags#12]
Hello, 

I am dealing with major issue here. I delayed update to newest version (4.37.0 but it happend first time around 4.32.0 version) of Statamic on my app, because I had an error resulting in crashing my whole website (except CP). I did not have time to debug it, but now is the time, and it seems that your addon breaks something resulting in:
`Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames` error

I managed to replicate it using Statamic cyberspace app (https://statamic.dev/quick-start-guide). Step by step I have added all collections, taxonomies, then scripts, Vite and so on. and it worked, ultill i've added my composer addons, then it crashed, so i knew something is not ok with this. Also removing `{{ metatags }}` in document "head" clears an error.

One by one, uninstalling addons, and when uninstalling yours, it started to working both in Cyberspace App, and my main project. So this has to be it. I do not have many more info about what can be the cause, only thing in debug stack is this:

`Gioppy
 \ StatamicMetatags\Tags\ MetatagsTags: 27 index` -> pointing to the same file caused "Title" bug i described you before: [https://github.com/gioppy/statamic-metatags/issues/10](https://github.com/gioppy/statamic-metatags/issues/10)
this line is highlighted:
`$page = collect($this->context->get('page'));`

Debug Bar throws an error here:

`Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames
C:/wamp64/www/a2mobile-www_wcag-lara--mk/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php#1023
Error
     * @param  mixed  $items
     * @return array<TKey, TValue>
     */
    protected function getArrayableItems($items)
    {
        if (is_array($items)) {
            return $items;`

I do not know it this helps but that's the only info I have right now, **please let me know if you can check this**, as for now either I will have to find another Metatags solution, or not update Statamic CMS. 

UPDATE: i've checked and from version 4.32.0 it is creating this "infinite loop" issue.

**Comment by barkinmeric** [comment]
I am having the same issue for php@8 and statamic@4.0. Is there any solution?

**Comment by gioppy** [comment]
You have right: the addon stop working from version 4.32 of Statamic. Apperently, it seams that `$this->context` inside of a tag has some changes. Now I have published a new versione (3.0.4) that have changed the way of retrieving data from page.
Thanks to all for support.
