### ISSUE TITLE
Class 'Statamic\Facades\Yaml' not found

### ISSUE THREAD

**Issue by tonybyng** [gioppy/statamic-metatags#2]
Hi

Im new to statamic but just installed your metatags plugin using composer, went to the control panel, clicked onto the meta tags option in the tools menu and then clicked on Settings and got

Class 'Statamic\Facades\Yaml' not found (vendor/gioppy/statamic-metatags/src/Settings.php:35)

Any pointers? This is running on Laravel 8

Thanks

Tony

**Comment by tonybyng** [comment]
Ive just seen someone else has reported this and it was closed but with no real resolution.

**Comment by gioppy** [comment]
Hi @tonybyng ,
Can you give me more information on your development environment?

**Comment by tonybyng** [comment]
Yep. Thanks for the quick reply. Its running on localhost at the moment with a php artisan serve.  I started with "statamic/starter-kit-cool-writings" starter kit and Ive only installed 7 addons at the moment - statamic impersonator, socialize, statamic-metatags, sitemap, tracking-code-manager and responsive-images - I can give you the full composer details if required

Running on linux mint and ive opted to have the users table run through eloquent (going to be moving 1000 users over so didnt want yaml files for that).   Not sure what other details you might need. Only installed on 7th January so its not an old system. 

oh yes and PHP 7.4.3

**Comment by gioppy** [comment]
Thanks! Tomorrow I try to recreate the environment and check if there are any problems. Even in the other similar issue I was unable to recreate the problem and it worked perfectly for me.

**Comment by tonybyng** [comment]
Think I've solved it. Did a bit of digging around and your Settings.php refers to Statamic\Facades\Yaml but in Statamic the namespace is Statamic\Facades\YAML (uppercase). Whilst I didnt think namespaces were case sensitive Ive just read the autoloaders are. I just changed the Settings.php in your vendor folder and it now works  ;-)

**Comment by gioppy** [comment]
Uh, strange. I have to investigate why I don't have this problem in my development environment. Thanks!

**Comment by gioppy** [comment]
I find what is the problem: the class is YAML not Yaml. Damn typo!!!!
Now is fixed.
