### ISSUE TITLE
Statamic 4

### ISSUE THREAD

**Issue by generator85** [gioppy/statamic-metatags#9]
Statamic 4 has been released, are you planning to add support?

**Comment by gioppy** [comment]
Yes, I planned to port on Statamic 4. But i cannot give a precise date as I'm very busy with other projects at the moment.

**Comment by Rndwiga** [comment]
@generator85 as we wait for @gioppy i found a quick workaround here https://github.com/rndrmu/statamic-metatags

**Comment by gioppy** [comment]
The addon is now compatible with Statamic 4. Please update to release 3.0.0.
